# Generated by Django 3.1.7 on 2021-04-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20210410_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=100)),
                ('Access', models.CharField(max_length=50)),
                ('Basic_Auth', models.BooleanField()),
                ('TLS_Client_Auth', models.BooleanField()),
                ('Skip_TLS_verify', models.BooleanField()),
                ('Forward_OAuth_identity', models.BooleanField()),
                ('With_Credentials', models.BooleanField()),
                ('With_CA_Cert', models.BooleanField()),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=30)),
                ('Trends', models.BooleanField()),
                ('After', models.IntegerField()),
                ('Range', models.IntegerField()),
                ('Cache_TTL', models.IntegerField()),
                ('Direct_DB_Connection', models.BooleanField()),
                ('Alerting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DB_DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(max_length=100)),
                ('DataBase', models.CharField(max_length=50)),
                ('User', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=30)),
                ('Max_Opens', models.IntegerField()),
                ('Max_Idels', models.IntegerField()),
                ('Max_Lifetime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Type', models.CharField(max_length=60)),
                ('Api_DataSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.api_datasource')),
                ('DB_DataSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.db_datasource')),
            ],
        ),
    ]
