# Generated by Django 3.1.7 on 2021-04-22 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_api_datasource_datasources_db_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasources',
            name='Api_DataSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.api_datasource'),
        ),
        migrations.AlterField(
            model_name='datasources',
            name='DB_DataSource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.db_datasource'),
        ),
    ]
