# Generated by Django 3.1.7 on 2021-04-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='ChartType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panels',
            name='Dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.dashboard'),
        ),
    ]
