# Generated by Django 3.1.7 on 2021-04-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_auto_20210425_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='Dashboard',
            field=models.IntegerField(),
        ),
    ]
