# Generated by Django 3.1.7 on 2021-04-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_auto_20210425_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panels',
            old_name='Dashboard',
            new_name='DashboardId',
        ),
    ]
