# Generated by Django 3.1.7 on 2021-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_auto_20210425_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Lable', models.CharField(max_length=50)),
                ('Hide', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('VariableScope', models.CharField(max_length=20)),
                ('PanelId', models.IntegerField()),
                ('DataSourceId', models.IntegerField()),
                ('Refresh', models.CharField(max_length=30)),
                ('Query', models.CharField(max_length=300)),
                ('Regex', models.CharField(max_length=200)),
                ('Sort', models.CharField(max_length=50)),
                ('MultiValue', models.BooleanField()),
                ('IncludeAllOptions', models.BooleanField()),
                ('ValueGroupTag', models.BooleanField()),
                ('CustomValues', models.CharField(max_length=100)),
                ('TextboxValues', models.CharField(max_length=80)),
                ('ConstantValue', models.CharField(max_length=80)),
                ('InstanceNameFilter', models.CharField(max_length=80)),
                ('IntervalValues', models.CharField(max_length=100)),
                ('IntervalAutoOption', models.BooleanField()),
            ],
        ),
    ]
