# Generated by Django 3.1.7 on 2021-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_datasource',
            name='Port',
            field=models.IntegerField(default=80),
        ),
    ]
