# Generated by Django 3.1.7 on 2021-05-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0012_auto_20210503_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_datasource',
            old_name='Port',
            new_name='Portt',
        ),
    ]
