# Generated by Django 3.1.7 on 2021-05-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0013_auto_20210503_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_datasource',
            old_name='Portt',
            new_name='Port',
        ),
    ]
