# Generated by Django 3.1.7 on 2021-05-23 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0014_auto_20210503_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanleDataSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.CharField(max_length=300)),
                ('DataSourceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.datasources')),
                ('PanelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.panels')),
            ],
        ),
    ]
