# Generated by Django 3.1.7 on 2021-05-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0015_panledatasources'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanleDataSources',
            new_name='Panel_DataSources',
        ),
    ]
