# Generated by Django 3.1.7 on 2021-05-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0016_auto_20210523_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel_datasources',
            old_name='DataSourceId',
            new_name='DataSource',
        ),
        migrations.RenameField(
            model_name='panel_datasources',
            old_name='PanelId',
            new_name='Panel',
        ),
    ]
