# Generated by Django 3.1.7 on 2021-05-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0017_auto_20210523_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel_datasources',
            old_name='DataSource',
            new_name='DataSources',
        ),
        migrations.RenameField(
            model_name='panel_datasources',
            old_name='Panel',
            new_name='Panels',
        ),
    ]
