# Generated by Django 3.1.7 on 2021-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0018_auto_20210523_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel_datasources',
            old_name='DataSources',
            new_name='DataSource',
        ),
        migrations.RemoveField(
            model_name='panel_datasources',
            name='Panels',
        ),
        migrations.AddField(
            model_name='panel_datasources',
            name='PanelId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
