# Generated by Django 3.1.7 on 2021-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0019_auto_20210523_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel_datasources',
            name='DataSource',
        ),
        migrations.AddField(
            model_name='panel_datasources',
            name='DataSourceId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
